env: dev
logging:
  level: debug
  type: console

server:
  corsAllowedOrigins:
    - http://localhost:3000

serial:
  portName: /tmp/ttyV0
  baudRate: 2400
  queueSize: 25

influx:
  enabled: false
  host: ""
  token: ""
  database: test
  organization: home

telegram:
  botName: "" #"@vms_core_bot"
  botApiKey: ""
  chatId: ""
  enableCommands: true
  users:
    - stefanopulze

